language: python
python:
  - "3.5"
  install:
  - pip install selenium
  - pip install sauceclient
  - pip install gitpython
# Added gitpython
#testing travis

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"


before_deploy:
- mkdir /tmp/test
- cd /tmp/test

repo = Repo.clone_from(
    'https://github.com/ole-vi/BeLL-Apps.git',
    '/tmp/test/',
    branch='inno'
    )
